services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management_db
    ports:
      - "54321:5432"
    volumes:
      - task_management_system_pg_data:/var/lib/postgresql/data

volumes:
  task_management_system_pg_data: