[tool.black]
line-length = 120
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.flake8]
ignore = ["ANN101", "W503"]
max-line-length = 120

[tool.mypy]
strict_optional = true
namespace_packages = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_defs = true
explicit_package_bases = true
plugins = "pydantic.mypy"
