"""added audit columns

Revision ID: 61448ad4ecb8
Revises: b4c2209e5175
Create Date: 2025-05-03 00:55:26.721687

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61448ad4ecb8"
down_revision: Union[str, None] = "b4c2209e5175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("board", sa.Column("created_by", sa.String(), nullable=False))
    op.add_column("board", sa.Column("updated_by", sa.String(), nullable=False))
    op.add_column("board", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("board", sa.Column("updated_at", sa.DateTime(), nullable=False))

    op.add_column("task", sa.Column("created_by", sa.String(), nullable=False))
    op.add_column("task", sa.Column("updated_by", sa.String(), nullable=False))
    op.add_column("task", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("task", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "updated_at")
    op.drop_column("task", "created_at")
    op.drop_column("task", "updated_by")
    op.drop_column("task", "created_by")

    op.drop_column("board", "updated_at")
    op.drop_column("board", "created_at")
    op.drop_column("board", "updated_by")
    op.drop_column("board", "created_by")
    # ### end Alembic commands ###
