"""added task and board tables

Revision ID: b4c2209e5175
Revises:
Create Date: 2025-05-02 15:42:24.369207

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4c2209e5175"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "task",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("board_uid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["board_uid"], ["board.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("board")
    # ### end Alembic commands ###
